base: 'https://www.hhhuerth.de'
baseVariants:
  -
    base: 'http://local.hhhuerth.de/'
    condition: 'applicationContext == "Development"'
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=4'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: default
    locale: de_DE
    iso-639-1: de
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    languageId: 0
rootPageId: 1
websiteTitle: ''
